axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 0  # Right thumb stick horizontal
scale_angular: 0.8
scale_angular_turbo: 1.5

enable_button: 1  # Left trigger button
enable_turbo_button: 0  # Right trigger button
